export const iconImages: { [key: string]: any } = {
  "1": require("../assets/icons/1.png"),
  "2": require("../assets/icons/2.png"),
  "3": require("../assets/icons/3.png"),
  "4": require("../assets/icons/4.png"),
  "5": require("../assets/icons/5.png"),
  "6": require("../assets/icons/6.png"),
  "7": require("../assets/icons/7.png"),
  "8": require("../assets/icons/8.png"),
  "11": require("../assets/icons/11.png"),
  "12": require("../assets/icons/12.png"),
  "13": require("../assets/icons/13.png"),
  "14": require("../assets/icons/14.png"),
  "15": require("../assets/icons/15.png"),
  "16": require("../assets/icons/16.png"),
  "17": require("../assets/icons/17.png"),
  "18": require("../assets/icons/18.png"),
  "19": require("../assets/icons/19.png"),
  "20": require("../assets/icons/20.png"),
  "21": require("../assets/icons/21.png"),
  "22": require("../assets/icons/22.png"),
  "23": require("../assets/icons/23.png"),
  "24": require("../assets/icons/24.png"),
  "25": require("../assets/icons/25.png"),
  "26": require("../assets/icons/26.png"),
  "29": require("../assets/icons/29.png"),
};
